// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { FooAPI } from './foo-api'
import { Foo, CopyFooToFooAPI } from './foo'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class FooService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FooServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private foosUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.foosUrl = origin + '/api/github.com/thomaspeugeot/bistack/go/v1/foos';
  }

  /** GET foos from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI[]> {
    return this.getFoos(GONG__StackPath, frontRepo)
  }
  getFoos(GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<FooAPI[]>(this.foosUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<FooAPI[]>('getFoos', []))
      );
  }

  /** GET foo by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {
    return this.getFoo(id, GONG__StackPath, frontRepo)
  }
  getFoo(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.foosUrl}/${id}`;
    return this.http.get<FooAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched foo id=${id}`)),
      catchError(this.handleError<FooAPI>(`getFoo id=${id}`))
    );
  }

  // postFront copy foo to a version with encoded pointers and post to the back
  postFront(foo: Foo, GONG__StackPath: string): Observable<FooAPI> {
    let fooAPI = new FooAPI
    CopyFooToFooAPI(foo, fooAPI)
    const id = typeof fooAPI === 'number' ? fooAPI : fooAPI.ID
    const url = `${this.foosUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FooAPI>(url, fooAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<FooAPI>('postFoo'))
    );
  }
  
  /** POST: add a new foo to the server */
  post(foodb: FooAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {
    return this.postFoo(foodb, GONG__StackPath, frontRepo)
  }
  postFoo(foodb: FooAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FooAPI>(this.foosUrl, foodb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted foodb id=${foodb.ID}`)
      }),
      catchError(this.handleError<FooAPI>('postFoo'))
    );
  }

  /** DELETE: delete the foodb from the server */
  delete(foodb: FooAPI | number, GONG__StackPath: string): Observable<FooAPI> {
    return this.deleteFoo(foodb, GONG__StackPath)
  }
  deleteFoo(foodb: FooAPI | number, GONG__StackPath: string): Observable<FooAPI> {
    const id = typeof foodb === 'number' ? foodb : foodb.ID;
    const url = `${this.foosUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FooAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted foodb id=${id}`)),
      catchError(this.handleError<FooAPI>('deleteFoo'))
    );
  }

  // updateFront copy foo to a version with encoded pointers and update to the back
  updateFront(foo: Foo, GONG__StackPath: string): Observable<FooAPI> {
    let fooAPI = new FooAPI
    CopyFooToFooAPI(foo, fooAPI)
    const id = typeof fooAPI === 'number' ? fooAPI : fooAPI.ID
    const url = `${this.foosUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<FooAPI>(url, fooAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<FooAPI>('updateFoo'))
    );
  }

  /** PUT: update the foodb on the server */
  update(foodb: FooAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {
    return this.updateFoo(foodb, GONG__StackPath, frontRepo)
  }
  updateFoo(foodb: FooAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<FooAPI> {
    const id = typeof foodb === 'number' ? foodb : foodb.ID;
    const url = `${this.foosUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FooAPI>(url, foodb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated foodb id=${foodb.ID}`)
      }),
      catchError(this.handleError<FooAPI>('updateFoo'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FooService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FooService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
