// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { BarAPI } from './bar-api'
import { Bar, CopyBarToBarAPI } from './bar'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class BarService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  BarServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private barsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.barsUrl = origin + '/api/github.com/thomaspeugeot/bistack/otherstack/go/v1/bars';
  }

  /** GET bars from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI[]> {
    return this.getBars(GONG__StackPath, frontRepo)
  }
  getBars(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<BarAPI[]>(this.barsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<BarAPI[]>('getBars', []))
      );
  }

  /** GET bar by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {
    return this.getBar(id, GONG__StackPath, frontRepo)
  }
  getBar(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.barsUrl}/${id}`;
    return this.http.get<BarAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched bar id=${id}`)),
      catchError(this.handleError<BarAPI>(`getBar id=${id}`))
    );
  }

  // postFront copy bar to a version with encoded pointers and post to the back
  postFront(bar: Bar, GONG__StackPath: string): Observable<BarAPI> {
    let barAPI = new BarAPI
    CopyBarToBarAPI(bar, barAPI)
    const id = typeof barAPI === 'number' ? barAPI : barAPI.ID
    const url = `${this.barsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BarAPI>(url, barAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BarAPI>('postBar'))
    );
  }
  
  /** POST: add a new bar to the server */
  post(bardb: BarAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {
    return this.postBar(bardb, GONG__StackPath, frontRepo)
  }
  postBar(bardb: BarAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BarAPI>(this.barsUrl, bardb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted bardb id=${bardb.ID}`)
      }),
      catchError(this.handleError<BarAPI>('postBar'))
    );
  }

  /** DELETE: delete the bardb from the server */
  delete(bardb: BarAPI | number, GONG__StackPath: string): Observable<BarAPI> {
    return this.deleteBar(bardb, GONG__StackPath)
  }
  deleteBar(bardb: BarAPI | number, GONG__StackPath: string): Observable<BarAPI> {
    const id = typeof bardb === 'number' ? bardb : bardb.ID;
    const url = `${this.barsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<BarAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted bardb id=${id}`)),
      catchError(this.handleError<BarAPI>('deleteBar'))
    );
  }

  // updateFront copy bar to a version with encoded pointers and update to the back
  updateFront(bar: Bar, GONG__StackPath: string): Observable<BarAPI> {
    let barAPI = new BarAPI
    CopyBarToBarAPI(bar, barAPI)
    const id = typeof barAPI === 'number' ? barAPI : barAPI.ID
    const url = `${this.barsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<BarAPI>(url, barAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BarAPI>('updateBar'))
    );
  }

  /** PUT: update the bardb on the server */
  update(bardb: BarAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {
    return this.updateBar(bardb, GONG__StackPath, frontRepo)
  }
  updateBar(bardb: BarAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarAPI> {
    const id = typeof bardb === 'number' ? bardb : bardb.ID;
    const url = `${this.barsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<BarAPI>(url, bardb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated bardb id=${bardb.ID}`)
      }),
      catchError(this.handleError<BarAPI>('updateBar'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in BarService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("BarService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
